---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || (yum install -y python3)
      become: true
      changed_when: false
    - name: install mkfs.ext4
      raw: test -e /usr/sbin/mkfs.ext4 || (yum install -y e4fsprogs)
      become: true
      changed_when: false
